action.yaml
=> feat: Add exit-code to Trivy args (#1)

action.yaml
=> chore: Update action metadata

README.md, action.yaml
=> docs: Update README.md

README.md, action.yaml
=> feat: Add severity arg

LICENSE, README.md
=> docs: Add badges

README.md, action.yaml
Signed-off-by: Simarpreet Singh <simar@linux.com>
=> docs: Fix docs and add improved example repo

README.md, action.yaml, workflow.yml
This adds an argument for the `vuln-type` parameter.
=> Add vuln-type parameter

Dockerfile, README.md, action.yaml, entrypoint.sh
[Issue](https://github.com/aquasecurity/trivy-action/issues/24)
[Closed PR](https://github.com/aquasecurity/trivy-action/pull/26) for discussions
=> Add scan type as option

entrypoint.sh
Fixes: https://github.com/aquasecurity/trivy-action/issues/28
Signed-off-by: Simarpreet Singh <simar@linux.com>
=> entrypoint: Remove \r from ignoreUnfixed option

entrypoint.sh
=> feat: suppress progress bar

README.md, action.yaml, entrypoint.sh
[Issue](https://github.com/aquasecurity/trivy-action/issues/23)
=> Added input option support

Dockerfile, entrypoint.sh
[Issue](https://github.com/aquasecurity/trivy-action/issues/40)
=> Pin docker image, and update skip dirs argument passing to trivy

Dockerfile
[Issue](https://github.com/aquasecurity/trivy-action/issues/22)
=> Update docker base image for trivy.

README.md, action.yaml, entrypoint.sh
Adding filtering vulnerabilities option through OPA rego
=> feat: add ignore-policy option to filter vulnerabilities

README.md, entrypoint.sh
* Added support of running rootfs command in github action
See in action: rahul2393/tracee@7dbc9ea and results https://github.com/rahul2393/tracee/runs/4322725088?check_suite_focus=true
Fixes: https://github.com/aquasecurity/trivy-action/issues/80
=> feat: added support for rootfs command

README.md, action.yaml, entrypoint.sh
=> feat(#59) add support to skip files

Dockerfile
Update to Latest Release of Trivy :)
=> Update to Latest Release of Trivy :) 

Dockerfile
Pinned new version of trivy, that fixed the sarif results related to https://github.com/aquasecurity/trivy/pull/1423
=> chore: update trivy version - fixed sarif

README.md, action.yaml, entrypoint.sh
When using fs mode add option to list of what security issues to detect
=> (feat) Add support for security-checks flag

README.md, action.yaml, entrypoint.sh
Related to #111 
You can see the two tests I have done there -> https://github.com/tanguy-platsec/trivy-action-security-checks-option-test/actions
=> Enable security checks option for image type

.gitignore, README.md, action.yaml, entrypoint.sh, test/data/.trivyignore1, test/data/.trivyignore2, test/data/image-trivyignores.test, test/test.bats
This PR adds support for supplying multiple ignorefiles to the action.
It also adds a test for the functionality, and adjusts a few minor test-related things. 👼🏻 
See #103 for the feature request.
=> Add support for --ignorefile option (.trivyignore)

entrypoint.sh
Fixes: #153 
Signed-off-by: Simar <simar@linux.com>
=> fix(sarif): Add timeout and security-checks for sarif

README.md
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>
Hi,
This PR corrects the example in the docs for config scan with sarif report.
=> docs: correct format and add output on config scan with sarif

.github/workflows/bump-trivy.yaml
See https://github.com/aquasecurity/trivy/issues/4829
We also need to create a PAT secret with a token with permissions: `repo` and `workflow`
=> ci: add workflow to bump trivy

Dockerfile, test/data/image-trivyignores.test, test/data/image.test
This will address bugs before 0.46.0
=> Update Dockerfile to 0.46.0

Dockerfile
To benefit from the changes in the release, see:
- https://github.com/aquasecurity/trivy/releases/tag/v0.47.0
In my case, particularly:
- https://github.com/aquasecurity/trivy/issues/5449
- https://github.com/aquasecurity/trivy/pull/5448
=> Update to `trivy` version `0.47.0` in Dockerfile

.github/workflows/build.yaml, Dockerfile
Upgrades Trivy from 0.48.1 to v0.49.0.
=> Upgrades Trivy from 0.48.1 to v0.49.0

.github/workflows/test.yaml, Dockerfile
=> bump trivy version to v0.51.2

.github/workflows/test.yaml, Dockerfile
Upgrade trivy version to v0.52.0, it's already out since 3 days ago 😄
=> Upgrade trivy to v0.52.0

.github/workflows/test.yaml, Dockerfile
=> Upgrade trivy to v0.52.2

Makefile
Hopefully trivial enough to go without previous issue :)
=> fix(Makefile): recursive option typo

.github/workflows/bump-trivy.yaml, README.md, workflow.yml
=> Upgrade GitHub actions

.github/workflows/test.yaml, README.md, action.yaml
Fixes https://github.com/aquasecurity/trivy/discussions/8625
Fixes https://github.com/aquasecurity/trivy/discussions/8630
=> Bump Trivy version to fix GitHub actions
