README.md

Closes #7 
Actions using `0.0.5` are failing with 
`(Line: 26, Col: 10): Unrecognized named-value: 'inputs'. Located at position 1 within expression: inputs.version`

Update README with 0.0.6 release

---

README.md
action.yaml

Closes #9
This PR adds support for `--ignore-unfixed` run argument.
I took the liberty and updated the README.me to point to tag `0.0.7`.
```yml
- name: Run scanner with --ignore-fixed=false
uses: zoispag/trivy-action@master
if: always()
with:
image-ref: 'image'
exit-code: '1'
severity: 'MEDIUM'
ignore-unfixed: false
- name: Run scanner with --ignore-fixed not set
uses: zoispag/trivy-action@master
if: always()
with:
image-ref: 'image'
exit-code: '1'
severity: 'MEDIUM'
- name: Run scanner with --ignore-fixed=true
uses: zoispag/trivy-action@master
if: always()
with:
image-ref: 'image'
exit-code: '1'
severity: 'MEDIUM'
ignore-unfixed: true
```
- **Run scanner with --ignore-fixed=false** executes: `docker.io/aquasec/trivy:latest  "image" "--format=table" "--ignore-unfixed=false" …

Feature: Add support for `--ignore-unfixed`

---

README.md
action.yaml

Adds the ability to output and save to a SARIF format file.
Requires: https://github.com/aquasecurity/trivy/pull/571 to be merged.
Signed-off-by: Simarpreet Singh <simar@linux.com>

SARIF: Add support for sarif output

---

README.md

I found this Action via the [Github blog post announcing the integration](https://github.blog/2020-10-07-announcing-third-party-code-scanning-tools-infrastructure-as-code-and-container-scanning/#trivvy-by-aqua-security) and had to take a detour via the Docker image listed in `action.yaml` to find the source and more on Trivy, so I think it'd be nice to have a direct link in the Readme. :smiley_cat:

Add a link to the Trivy repository to the Readme

---

entrypoint.sh

Fixes #50 
As per Trivy usage (https://aquasecurity.github.io/trivy/v0.18.3/usage/) --cache-dir is a global options and should be passed before the command.
With that change I'm able to run the Trivy action with the `cache-dir` input defined and without getting any error.
I've mirrored the `$ARGS` logic as `$GLOBAL_ARGS` in case support for other global options is required in the future. However, so far I've left `$GLOBAL_ARGS` out of the info statement: `Running trivy with options: ...` as I wasn't sure if this is needed for global options and if it is how best to include it; suggestions welcome.

Pass --cache-dir as global argument to Trivy

---

Dockerfile
README.md
action.yaml
entrypoint.sh

This PR resolves https://github.com/aquasecurity/trivy-action/issues/54
and is a follow up to https://github.com/aquasecurity/trivy-action/pull/55
Example output running with the below action params:
scan-type: 'config'
hide-progress: false
format: 'table'
severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

Enable config scanning

---

Dockerfile

Fix https://github.com/aquasecurity/trivy-action/issues/57
- Bumps the base trivy image to 0.19.2 to fix an issue where config scanning breaks.

Bump base image version to 0.19.2 to fix issue with config scanning.

---

entrypoint.sh

See in action: rahul2393@225e714
and results: https://github.com/rahul2393/tracee/actions/runs/1444404833 and https://github.com/rahul2393/tracee/security/code-scanning
Fixes: https://github.com/aquasecurity/trivy-action/issues/77

chore: Include skip options when building SARIF report

---

README.md
action.yaml
entrypoint.sh

Add list-all-pkgs option for https://github.com/aquasecurity/trivy-action/issues/86
- Add list-all-pkgs usage to README
- Add `list-all-pkgs` option to action.yaml and entrypoint.sh

feat: Add list-all-pkgs option

---

README.md

This PR updates the default value of the `timeout` configuration mentioned in `README.md` with reference to the original documentation https://aquasecurity.github.io/trivy/v0.23.0/getting-started/cli/config/

Update default value of timeout configuration

---

Dockerfile

Updating the trivy version. I tested the main options -a image, -a config, -a rootfs.

chore: Update trivy version to 0.25

---

Dockerfile

Update the Dockerfile to use the latest release of Trivy.
The version of Trivy used in the action currently has errors when generating table output for scans of some files. The latest version, 0.28.1 has fixed these errors.

Update Trivy Version in Dockerfile

---

Dockerfile

Unfortunately, using the Trivy action repeatedly in the CI can cause them to fail because of DockerHub pull rate limiting.
One shall not get this issue by using the public AWS ECR.
[Here is a test run](https://github.com/tanguy-platsec/trivy-ecr-testing/runs/6725884119?check_suite_focus=true) on a private repository to prove the pull works properly of course.
Please let me know of the reason the action uses the image from DockerHub if there is one.

Use AWS public ECR instead of rate-limiting dockerhub

---

README.md
workflow.yml

Hi :wave: 
Description :
- This PR updates the `github/codeql-action/upload-sarif` action from `v1` to `v2`.
Reason:
- The `v1` of this action is deprecated and there is a warning annotation each time you run it:
```
CodeQL Action v1 will be deprecated on December 7th, 2022. Please upgrade to v2. For more information, 
see https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
```
David
Signed-off-by: David <davidcalvertfr@gmail.com>

feat: update codeql-action/upload-sarif to v2

---

README.md

This just adds an option to the README which was not documented.

Add missing option to README.

---

README.md
action.yaml

I simply added the missing HTML template in the README.md and action.yaml files, and removed the deprecated SARIF template (https://github.com/aquasecurity/trivy/discussions/1571) from the action.yaml file.

docs: added missing HTML template and removed deprecated SARIF template

---

Makefile
README.md
entrypoint.sh
test/data/trivy.yaml
test/data/yamlconfig.test
test/test.bats

Also adds some documentation explaining how the config
and flags are used in conjunction with each other.
Fixes: https://github.com/aquasecurity/trivy-action/issues/147
Signed-off-by: Simar <simar@linux.com>

fix(config): Drop mixing of options with yaml config.

---

entrypoint.sh

Curl in line 189 incorrectly provides credentials to the github dependency submission API.

Fix github dependency submission API call

---

README.md

I was searching for an option to add --full-license and found out that you can add trivy.yaml. I realised this was missing from the table in the README, which was for me the first place I searched for this functionaltiy.

docs: add trivy-config to table

---

README.md
action.yaml
entrypoint.sh
test/test.bats

Fixes https://github.com/aquasecurity/trivy-action/issues/210 
```
WARN	'--security-checks' is deprecated. Use '--scanners' instead.
```

Rename security-checks to scanners

---

entrypoint.sh
test/data/trivy-reduced.yaml
test/test.bats

This builds on an existing pull request by [leongyh](https://github.com/leongyh): https://github.com/aquasecurity/trivy-action/pull/207
Previously, arguments provided using regular flags were ignored if a trivy config file was provided
Note that this pull request makes no effort to deduce or merge desired argument if the same configuration with different values are provided both within the config file and as flags. Behaviour for this case would develop on the implementation of trivy.

Include args when using trivy config file

---

entrypoint.sh

Changes:
Disable script fails when run trivy scan.
Test:
Work at expect.

Enhance GitHub Dependency Snapshot upload

---

entrypoint.sh

Add exit-code parameter to sarif format execution.
Prior to version v0.9.0, Sarif format execution with `--exit-code` parameter was failing if any vulnerability found, this is because Trivy was run twice (sarif and silent + normal execution). As of > v0.9.0 exit-code does not work anymore.
We find it valuable in case you want to chain or perform different actions if the scanning fails.

feat: add exit-code parameter to sarif format

---

action.yaml

Attribute `image-ref` of action is marked as required. But we don't set it and it works. So it is not actually required.
Would be nice to fix this minor things, because Github Actions extension/linter complains about it.
Fixing https://github.com/aquasecurity/trivy-action/issues/260

fix: mark image-ref attribute optional

---

Dockerfile

This update fixes https://github.com/aquasecurity/trivy/issues/5441

Update Dockerfile to 0.46.1

---

entrypoint.sh

This change moves the return code to outside the trivy call. This fixes #228 as the return code was not being propagated.

fix: set return code after each Trivy call

---

entrypoint.sh

* Adds filesystem to scan-type.
* resolves: [scan-ref doesn't work when using filesystem instead of fs](https://github.com/aquasecurity/trivy-action/issues/264)

feature: add filesystem alias

---

README.md
action.yaml
entrypoint.sh
test/data/config-sarif.test
test/data/config.test
test/data/dev.tfvars
test/data/fs-scheck.test
test/data/main.tf
test/data/tfvars.test
test/data/yamlconfig.test
test/test.bats

Adds support for `--tf-vars` by adding to the `entrypoint.sh` and `action`. We've tested this internally by pointing our Trivy to my fork of Trivy and passing the required parameters.

feature(config): add terraform variable files

---

README.md

There are flags not supported by [inputs](https://github.com/aquasecurity/trivy-action#inputs).
We need to write about ways to configure these flags by ENVs and config file.
- Close #292

docs: add configuration info for flags not supported by inputs

---

entrypoint.sh

Added the possibility to use `skip-files` and `hide-progress` options when using Sarif as report format.

fix: Fix `skip-files` and `hide-progress` options not being applied when using Sarif report format

---

README.md

Relates to https://github.com/aquasecurity/trivy-action/issues/286
Since https://github.com/aquasecurity/trivy/pull/5999 should fix the underlying issue, the only problem left is that 
> users of `trivy-action` would currently have no way of finding out the `filePath` of each package when using the github format.
A solution for this issue is to update the documentation by:
- mentioning Github Dependency isn't showing all the details.
- users should parse the output JSON if they need more details.
- provide an example of how to save the outputs as an artifact in Github so it's easy to later download it.
I also took the opportunity to give an example of how to scan an image in a private registry as documentation was lacking.

docs(report): improve documentation around `Using Trivy to generate SBOM` and sending it to Github

---

entrypoint.sh

Fix: #173
When `scan-type` is "sbom", the key to specify the target SBOM file should be `scan-ref`, not `image-ref`. This pull request makes a minor modification to ensure that when `scan-type` is "sbom", `scanRef` is specified for `artifactRef` within `entrypoint.sh`.

fix: Refer to scan-ref when scan-type is "sbom"

---

README.md
action.yaml
entrypoint.sh

I tried to use [this](https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#using-trivy-to-scan-infrastructure-as-code) example, but Trivy is returning an error, when defining `hide-progress: false` or `hide-progress: true` input.
This PR allows Trivy to use the correct `--quiet` flag, instead of non existing `--no-progress`.

Make 'hide-progress' input working again

---

README.md

In case you don't have GitHub Advanced Security license and need to browse security reports for private repositories, you can publish them to `$GITHUB_STEP_SUMMARY` variable.
As the result, reports will be available in the GitHub workflow summary:

Browse Trivy reports without GitHub Advanced Security license

---

README.md
action.yaml
entrypoint.sh

- This is a fix to the closed #267
There was a config issue where we checked to see if the `docker-host` has set to `true`, but it should check that it has value...
Also took the liberty of updating the docs and example
Thank you all so much for the quick fixes and merging :)

Fix docker host bug

---

entrypoint.sh

resolved: #337 
Allow trivy-config and other options to be used together.

fix: 🐛 allow trivy-config and other options to be used together

---

README.md

Due to the large number of `TOOMANYREQUESTS` errors - it makes sense to use `cache`
Add information on how to use `action/cache`
Test runs:
- save in cache - https://github.com/DmitriyLewen/test-trivy-action/actions/runs/11158340123/job/31014411967
- restore from cache - https://github.com/DmitriyLewen/test-trivy-action/actions/runs/11158358025/job/31014469696

docs: add usage info about `action/cache` for trivy databases

---

.github/workflows/bump-trivy.yaml
.github/workflows/test.yaml
Dockerfile
README.md
action.yaml
entrypoint.sh
test/test.bats

Store DBs and checks bundle in the cache by default by using `actions/cache` to mitigate `429 TOOMANYREQUESTS`.
- Rewrite a docker action to [a composite action](https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action)
- Remove Dockerfile
- Use `actions/cache` to store DBs and checks bundle in cache
- Update inputs
- Set the default value to `cache-dir`
- Add `version`
- Delete unused `artifact-type`
- Fix tests

feat: store artifacts in cache by default

---

action.yaml

For some runners there is a problem with `curl` and `sudo` when installing Trivy.
See #403 for details
So we need to use [setup-trivy](https://github.com/aquasecurity/setup-trivy/) to install Trivy.
Test runs:
- https://github.com/DmitriyLewen/test-trivy-action/actions/runs/11252839297
- https://github.com/DmitriyLewen/test-trivy-action/actions/runs/11252890226
- Close #403

ci: use `setup-trivy` to install Trivy

---

README.md
action.yaml

If a user is invoking the action multiple times then the trivy binary gets installed multiple times.  Users can avoid this by managing the installation themselves and setting the skip-setup input to true, or by letting the action install in on their first invocation and then setting skip-setup to true on subsequent invocations
This is an alternative solution to aquasecurity/setup-trivy#7 as discussed in that PR to address aquasecurity/setup-trivy#6
By allowing users to control whether the call to the `setup-trivy` action is made they can control how the `trivy` binary is installed, and avoid installing it multiple times if they have workflows that call `trivy` multiple times.
Added an example test at https://github.com/rvesse/setup-trivy-debugging/blob/main/.github/workflows/setup-trivy-in …

feat: Allow skipping setup

---

README.md

Since the latest ubuntu image has been updated to ubuntu 24.04 and "oras" command not found in the new image
reference: https://github.com/Tiryoh/docker-ros2-desktop-vnc/pull/186

Fix oras command not found in "Update Trivy Cache" action

---

README.md
action.yaml

There are cases when we need to overwrite token for `actions/checkout` in `setup-trivy`.
e.g. GHES - #418, https://github.com/aquasecurity/setup-trivy/issues/10
So we need to add a `token-setup-trivy` input to add the ability to override the default `token`.
test runs:
- invalid `token-setup-trivy` - https://github.com/DmitriyLewen/test-trivy-action/actions/runs/11493317116
- `token-setup-trivy` with read perms only - https://github.com/DmitriyLewen/test-trivy-action/actions/runs/11493314425
- `token-setup-trivy` is not specified -  https://github.com/DmitriyLewen/test-trivy-action/actions/runs/11493303718
- Close #418 
- https://github.com/aquasecurity/setup-trivy/issues/10

feat: add token for `setup-trivy`

---

README.md

As part of PR #434 the default trivy version got bumped but the readme didn't reflect it.
CC: @simar7

fix: Update default trivy version in README

---

action.yaml

Small typo found in the description for an input in the `action.yaml` file.

fix: typo in description of an input for action.yaml

---

README.md

Update the README.md SBOM section
* Use logical workflow name
* Use modern ubuntu version

Improve README/SBOM

---

README.md
action.yaml
entrypoint.sh
test/test.bats

As discussed in #422 the current way that the Trivy action injects the GitHub Actions inputs to `trivy` is by adding these to the `GITHUB_ENV` file which is then used to populate the environment for all subsequent job steps.  This leads to a problem where a subsequent call to `aquasecurity/trivy-action` may incorrectly pick up inputs from a previous call because those previous inputs are already set in the environment file, and the action only sets those environment variables to new values if the new inputs differ from the defaults.
This PR takes an approach that @DmitriyLewen was already developing in his fork and finishes it up ready for review.  Basically instead of writing the inputs to the `GITHUB_ENV` file it writes them, in the form of `export <var>=<value>` statements to a …

Fix Trivy action inputs leaking between invocations (#422)

---

action.yaml

Fixes #423
Pin `aquasecurity/setup-trivy` to hash instead of a tag so that GitHub Actions
["allowing select actions" feature](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#allowing-select-actions-and-reusable-workflows-to-run) can be used to whitelist the dependent action by a hash.
This is needed since some organizations have a policy to only allow pinned 3rd party actions to
be used. ["Pin actions to a full length commit SHA"](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) is recommended by GitHub and many organizations follow this best practice.
It's not …

Pin aquasecuriy/setup-trivy to hash instead of tag

---

README.md

Fixing error in the README.md. I was confused that the `image-ref: '.'` was specified for `scan-type: 'fs'`. I believe the intent is to set `scan-ref: '.'`.

doc: correct sbom fs scan
